site_name: 栈底

nav:
  - 计算机科学: 
    - 简介: cs/index.md
    - 工具:
      - GitHub: cs/tools/github/index.md
  - 物理基础:
    - 电子学:
      - 数字电子技术基础: physics\electronics\digital_electronics.md

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode


plugins:
    - search:
    # - encryptcontent: 
    #     global_password: ""
    #     title_prefix: '[已加密]'
    #     summary: '本篇文章已加密'
    #     placeholder: '请在此输入密码......'
    #     decryption_failure_message: '密码错误，请重新输入。'
    #     encryption_info_message: ''
    #     password_button: True
    #     password_button_text: '点此解密'
    #     encrypted_something:
    #         md-nav md-nav--secondary: [nav , class]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences


# add mathjax support
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#supported-extensions
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css: 
  - stylesheets/slates.css
