site_name: 小栈

nav:
  - 计算机科学: 
    - 简介: cs/index.md
    - 计算机网络理论:
      - 简介: cs/networking/index.md
    - 编译原理:
      - 概论: cs/compilers/index.md
      - 前置知识: cs/compilers/chap1.md
      - 词法分析: cs/compilers/chap3.md
      - 语法分析: cs/compilers/chap4.md
      - 语法制导的语义翻译: cs/compilers/chap5.md
      - 中间代码生成及优化: cs/compilers/chap6.md
    - 工具:
      - GitHub: cs/tools/github/index.md
      - 正则表达式: cs/tools/reg/index.md
      - ANTLR:
        - 简介: cs/tools/antlr/index.md
  - 数学基础:
    - 简介: math/index.md
    - 微积分:
      - 简介: math/calculus/index.md
      - 复函数: math/calculus/complex_functions.md
    - 线性代数:
      - 简介: math/linear_algebra/index.md
      - 技巧: math/linear_algebra/techniques.md
    - 概率论:
      - 简介: math/probability/index.md
      - 事件、概率: math/probability/basic_concepts.md
      - 随机变量: 
        - 随机变量的定义: math/probability/random_variables.md
        - 常见随机变量分布: math/probability/distribution.md
        - 随机变量的数字特征: math/probability/variables_number_feature.md
      - 应用:
        - 概率不等式: math/probability/unequalities.md
        - 极限定理与估计:  math/probability/limitation_theorem.md

      - 作业题选摘: math/probability/selected_homework.md
      - 习题课选摘: math/probability/selected_exercise.md
  - 物理基础:
    - 电子学:
      - 简介: physics\electronics\index.md
      - 数字电路: 
          - 组合逻辑电路: physics\electronics\digital_electronics.md
          - 时序逻辑电路: physics\electronics\5.md
  - 实用工具:
    - 简介: tools/index.md
    - 文献工具: tools/citations.md
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode


plugins:
    - search:
    # - encryptcontent: 
    #     global_password: ""
    #     title_prefix: '[已加密]'
    #     summary: '本篇文章已加密'
    #     placeholder: '请在此输入密码......'
    #     decryption_failure_message: '密码错误，请重新输入。'
    #     encryption_info_message: ''
    #     password_button: True
    #     password_button_text: '点此解密'
    #     encrypted_something:
    #         md-nav md-nav--secondary: [nav , class]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes


# add mathjax support
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#supported-extensions
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css: 
  - stylesheets/slates.css
